/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CandidateReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "candidate";
};

export type ClientReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "client";
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type Placement = {
  _id: string;
  _type: "placement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  candidate: CandidateReference;
  client: ClientReference;
  recruiter: TeamMemberReference;
  jobTitle: string;
  engagementType?: "permanent" | "contract" | "contract_to_hire" | "temporary";
  workArrangement?: "onsite" | "hybrid" | "remote" | "flexible";
  workLocation?: string;
  clientReference?: string;
  baseSalary: number;
  feeMode: "percentage" | "flat";
  feePercentage?: number;
  flatFeeAmount?: number;
  gstPercentage?: number;
  feeAmount?: number;
  gstAmount?: number;
  totalInvoiceValue?: number;
  placementDate: string;
  offerAcceptedDate?: string;
  probationPeriodDays?: number;
  probationEndDate?: string;
  invoiceDate?: string;
  exitDate?: string;
  paymentDueDate?: string;
  revenueStatus?: "pending" | "invoiced" | "paid" | "deducted" | "partially_paid";
  invoiceNumber?: string;
  paymentDate?: string;
  amountReceived?: number;
  notes?: string;
  createdAt?: string;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName: string;
  legalName?: string;
  industry?:
    | "it_software"
    | "banking_finance"
    | "healthcare"
    | "manufacturing"
    | "ecommerce"
    | "consulting"
    | "education"
    | "telecom"
    | "retail"
    | "other";
  gstin?: string;
  pan?: string;
  contacts: Array<{
    name: string;
    designation?: string;
    email: string;
    phone?: string;
    isActive?: boolean;
    isPrimary?: boolean;
    _type: "contact";
    _key: string;
  }>;
  billingEmail?: string;
  billingAddress?: string;
  website?: string;
  feeModel?: "percent_ctc" | "flat_per_hire";
  agreementFeePercentage?: number;
  paymentTerms?: number;
  msaStartDate?: string;
  msaEndDate?: string;
  leadSource?: "inbound" | "referral" | "outbound" | "job_board" | "event" | "expansion" | "other";
  status?: "active" | "inactive" | "prospect" | "on_hold";
  notes?: string;
  createdAt?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Candidate = {
  _id: string;
  _type: "candidate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName: string;
  email?: string;
  phone?: string;
  alternateEmail?: string;
  alternatePhone?: string;
  primarySkill: string;
  skills?: Array<string>;
  experience?: number;
  currentCompany?: string;
  currentDesignation?: string;
  currentLocation?: string;
  preferredLocations?: Array<string>;
  willingToRelocate?: boolean;
  remotePreference?: "onsite" | "hybrid" | "remote" | "flexible";
  languages?: Array<string>;
  highestEducation?: string;
  currentSalary?: number;
  expectedSalary?: number;
  noticePeriod?: number;
  status:
    | "immediately_available"
    | "available_next_30_days"
    | "on_notice_period"
    | "not_available"
    | "on_hold"
    | "placed";
  linkedInUrl?: string;
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  assignedRecruiter?: TeamMemberReference;
  source?: "linkedin" | "naukri" | "referral" | "job_portal" | "direct" | "other";
  lastContactedAt?: string;
  nextFollowUpAt?: string;
  notes?: string;
  createdAt?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  email: string;
  role: "trainee" | "recruiter" | "senior_recruiter" | "team_lead" | "manager" | "founder_ceo";
  workStatus: "full_time" | "part_time" | "contract" | "intern";
  specializations?: Array<string>;
  phone?: string;
  isActive?: boolean;
  joinedAt: string;
  leftAt?: string;
  incentivePercentage?: number;
  notes?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CandidateReference
  | ClientReference
  | TeamMemberReference
  | Placement
  | Client
  | SanityFileAssetReference
  | Candidate
  | TeamMember
  | MediaTag
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/query.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && language == $language][0] {  ...,}
export type SettingsQueryResult = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "settings" && language == $language][0] {\n  ...,\n}': SettingsQueryResult;
  }
}
