import { Suspense } from "react";
import { Header } from "@/components/layout/header";
import { StatsCard } from "@/components/dashboard/stats-card";
import { getTeamMembers, getPlacements } from "@/lib/sanity-queries";
import { UserCog, Users, Trophy, ExternalLink, Mail, Phone } from "lucide-react";
import { cn } from "@/lib/utils";

const roleLabels: Record<string, string> = {
  recruiter: "Recruiter",
  senior_recruiter: "Senior Recruiter",
  team_lead: "Team Lead",
  manager: "Manager",
};

function formatCurrency(value: number): string {
  if (value >= 10000000) {
    return `₹${(value / 10000000).toFixed(2)}Cr`;
  }
  if (value >= 100000) {
    return `₹${(value / 100000).toFixed(1)}L`;
  }
  return `₹${value.toLocaleString("en-IN")}`;
}

function TeamSkeleton() {
  return (
    <div className="animate-pulse space-y-6 p-6">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-28 rounded-xl bg-card" />
        ))}
      </div>
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-64 rounded-xl bg-card" />
        ))}
      </div>
    </div>
  );
}

async function TeamContent() {
  const [teamMembers, placements] = await Promise.all([
    getTeamMembers(),
    getPlacements(),
  ]);

  const activeMembers = teamMembers.filter((m) => m.isActive);

  // Calculate stats per team member
  const memberStats = teamMembers.map((member) => {
    const memberPlacements = placements.filter(
      (p) => p.recruiter?._id === member._id
    );
    const totalRevenue = memberPlacements.reduce(
      (sum, p) => sum + (p.totalInvoiceValue || 0),
      0
    );
    const paidRevenue = memberPlacements
      .filter((p) => p.revenueStatus === "paid")
      .reduce((sum, p) => sum + (p.amountReceived || p.totalInvoiceValue || 0), 0);

    return {
      ...member,
      placements: memberPlacements.length,
      totalRevenue,
      paidRevenue,
    };
  });

  const totalRevenue = memberStats.reduce((sum, m) => sum + m.totalRevenue, 0);

  return (
    <div className="space-y-6 p-6">
      {/* Stats Summary */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatsCard
          title="Team Members"
          value={teamMembers.length}
          subtitle={`${activeMembers.length} active`}
          icon={UserCog}
        />
        <StatsCard
          title="Total Placements"
          value={placements.length}
          subtitle="By all recruiters"
          icon={Users}
        />
        <StatsCard
          title="Total Revenue"
          value={formatCurrency(totalRevenue)}
          subtitle="Generated by team"
          icon={Trophy}
          variant="success"
        />
      </div>

      {/* Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-foreground">Team Members</h2>
        <a
          href="/studio/structure/teamMember"
          target="_blank"
          className="flex h-9 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
        >
          Manage in Studio
          <ExternalLink className="h-3 w-3" />
        </a>
      </div>

      {/* Team Cards */}
      {memberStats.length === 0 ? (
        <div className="rounded-xl border border-border bg-card p-8 text-center">
          <p className="text-muted-foreground">No team members yet</p>
          <a
            href="/studio/structure/teamMember"
            target="_blank"
            className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline"
          >
            Add team members in Sanity Studio
            <ExternalLink className="h-3 w-3" />
          </a>
        </div>
      ) : (
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {memberStats.map((member, index) => (
            <div
              key={member._id}
              className="rounded-xl border border-border bg-card p-5 transition-colors hover:border-border-hover"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary-muted text-lg font-semibold text-primary">
                    {member.name
                      .split(" ")
                      .map((n) => n[0])
                      .join("")
                      .toUpperCase()
                      .slice(0, 2)}
                  </div>
                  <div>
                    <h3 className="font-medium text-foreground">{member.name}</h3>
                    <p className="text-sm text-muted-foreground">
                      {member.role ? roleLabels[member.role] || member.role : "Recruiter"}
                    </p>
                  </div>
                </div>
                <span
                  className={cn(
                    "inline-flex rounded-full px-2 py-0.5 text-xs font-medium",
                    member.isActive
                      ? "bg-success/20 text-success"
                      : "bg-muted text-muted-foreground"
                  )}
                >
                  {member.isActive ? "Active" : "Inactive"}
                </span>
              </div>

              <div className="mt-4 grid grid-cols-2 gap-4 border-t border-border pt-4">
                <div>
                  <p className="text-xs text-muted-foreground">Placements</p>
                  <p className="text-lg font-semibold text-foreground">
                    {member.placements}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Revenue</p>
                  <p className="text-lg font-semibold text-foreground">
                    {formatCurrency(member.totalRevenue)}
                  </p>
                </div>
              </div>

              <div className="mt-4 flex items-center gap-2 border-t border-border pt-4">
                {member.email && (
                  <a
                    href={`mailto:${member.email}`}
                    className="flex h-8 flex-1 items-center justify-center gap-2 rounded-lg bg-muted text-sm text-muted-foreground transition-colors hover:bg-card-hover hover:text-foreground"
                  >
                    <Mail className="h-3.5 w-3.5" />
                    Email
                  </a>
                )}
                {member.phone && (
                  <a
                    href={`tel:${member.phone}`}
                    className="flex h-8 flex-1 items-center justify-center gap-2 rounded-lg bg-muted text-sm text-muted-foreground transition-colors hover:bg-card-hover hover:text-foreground"
                  >
                    <Phone className="h-3.5 w-3.5" />
                    Call
                  </a>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function TeamPage() {
  return (
    <div className="flex flex-col">
      <Header
        title="Team"
        subtitle="Manage your recruitment team"
      />
      <Suspense fallback={<TeamSkeleton />}>
        <TeamContent />
      </Suspense>
    </div>
  );
}
