import {Suspense} from "react";
import {Header} from "@/components/layout/header";
import {StatsCard} from "@/components/dashboard/stats-card";
import {getTeamMembers, getPlacements} from "@/lib/sanity-queries";
import {UserCog, Users, Trophy, ExternalLink, Mail, Phone} from "lucide-react";
import {cn} from "@/lib/utils";
import {Card, CardContent, CardHeader} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";

const roleLabels: Record<string, string> = {
  recruiter: "Recruiter",
  senior_recruiter: "Senior Recruiter",
  team_lead: "Team Lead",
  manager: "Manager",
};

function formatCurrency(value: number): string {
  if (value >= 10000000) {
    return `₹${(value / 10000000).toFixed(2)}Cr`;
  }
  if (value >= 100000) {
    return `₹${(value / 100000).toFixed(1)}L`;
  }
  return `₹${value.toLocaleString("en-IN")}`;
}

function TeamSkeleton() {
  return (
    <div className="animate-pulse space-y-6 p-6">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-28 rounded-lg bg-muted" />
        ))}
      </div>
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-64 rounded-lg bg-muted" />
        ))}
      </div>
    </div>
  );
}

async function TeamContent() {
  const [teamMembers, placements] = await Promise.all([getTeamMembers(), getPlacements()]);

  const activeMembers = teamMembers.filter((m) => m.isActive);

  const memberStats = teamMembers.map((member) => {
    const memberPlacements = placements.filter((p) => p.recruiter?._id === member._id);
    const totalRevenue = memberPlacements.reduce((sum, p) => sum + (p.totalInvoiceValue || 0), 0);
    const paidRevenue = memberPlacements
      .filter((p) => p.revenueStatus === "paid")
      .reduce((sum, p) => sum + (p.amountReceived || p.totalInvoiceValue || 0), 0);

    return {
      ...member,
      placements: memberPlacements.length,
      totalRevenue,
      paidRevenue,
    };
  });

  const totalRevenue = memberStats.reduce((sum, m) => sum + m.totalRevenue, 0);

  return (
    <div className="space-y-6 p-6">
      {/* Stats Summary */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <StatsCard
          title="Team Members"
          value={teamMembers.length}
          description={`${activeMembers.length} active`}
          icon={UserCog}
        />
        <StatsCard
          title="Total Placements"
          value={placements.length}
          description="By all recruiters"
          icon={Users}
        />
        <StatsCard
          title="Total Revenue"
          value={formatCurrency(totalRevenue)}
          description="Generated by team"
          icon={Trophy}
          variant="success"
        />
      </div>

      {/* Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold tracking-tight text-foreground">Team Members</h2>
        <a
          href="/studio/structure/teamMember"
          target="_blank"
          className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-all duration-150 hover:bg-primary/90 active:scale-[0.98]"
        >
          Manage in Studio
          <ExternalLink className="h-3 w-3" />
        </a>
      </div>

      {/* Team Cards */}
      {memberStats.length === 0 ? (
        <Card className="p-8 text-center">
          <p className="text-muted-foreground">No team members yet</p>
          <a
            href="/studio/structure/teamMember"
            target="_blank"
            className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline"
          >
            Add team members in Sanity Studio
            <ExternalLink className="h-3 w-3" />
          </a>
        </Card>
      ) : (
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {memberStats.map((member) => (
            <Card key={member._id} className="transition-shadow hover:shadow-md">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="flex h-11 w-11 items-center justify-center rounded-full bg-primary/10 text-base font-semibold text-primary">
                      {member.name
                        .split(" ")
                        .map((n) => n[0])
                        .join("")
                        .toUpperCase()
                        .slice(0, 2)}
                    </div>
                    <div>
                      <h3 className="font-medium text-foreground">{member.name}</h3>
                      <p className="text-sm text-muted-foreground">
                        {member.role ? roleLabels[member.role] || member.role : "Recruiter"}
                      </p>
                    </div>
                  </div>
                  <Badge variant={member.isActive ? "success" : "secondary"}>
                    {member.isActive ? "Active" : "Inactive"}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4 border-t border-border pt-4">
                  <div>
                    <p className="text-xs text-muted-foreground">Placements</p>
                    <p className="text-xl font-bold text-foreground">{member.placements}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Revenue</p>
                    <p className="text-xl font-bold text-foreground">
                      {formatCurrency(member.totalRevenue)}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2 border-t border-border pt-4">
                  {member.email && (
                    <a
                      href={`mailto:${member.email}`}
                      className="flex flex-1 h-8 items-center justify-center gap-2 rounded-md bg-secondary text-sm font-medium text-secondary-foreground shadow-sm transition-colors hover:bg-secondary/80"
                    >
                      <Mail className="h-3.5 w-3.5" />
                      Email
                    </a>
                  )}
                  {member.phone && (
                    <a
                      href={`tel:${member.phone}`}
                      className="flex flex-1 h-8 items-center justify-center gap-2 rounded-md bg-secondary text-sm font-medium text-secondary-foreground shadow-sm transition-colors hover:bg-secondary/80"
                    >
                      <Phone className="h-3.5 w-3.5" />
                      Call
                    </a>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

export default function TeamPage() {
  return (
    <div className="flex flex-col">
      <Header title="Team" subtitle="Manage your recruitment team" />
      <Suspense fallback={<TeamSkeleton />}>
        <TeamContent />
      </Suspense>
    </div>
  );
}
